apiVersion: v1
kind: Service
metadata:
  name: piagent
  namespace: '{{ .Release.Namespace }}'
spec:
  type: ClusterIP
  selector: { io.kompose.service: piagent }
  ports:
  - { name: tcp, port: 80, targetPort: 80 }
