apiVersion: v1
kind: Secret
metadata:
  name: visionbridge-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
data:
  LOGIN_PASSWORD: '{{ .Values.olaresEnv.LOGIN_PASSWORD | default "change-me" | b64enc }}'